//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebMedia.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Album
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Album()
        {
            this.Anhs = new HashSet<Anh>();
        }
    
        public int ID_Album { get; set; }
        public string TenAlbum { get; set; }
        public Nullable<int> SoLuongAnh { get; set; }
        public int ID_ChuDe { get; set; }
        public int ID_NguoiChup { get; set; }
        public string NoiDung { get; set; }
        public string AnhBia { get; set; }
    
        public virtual ChuDe ChuDe { get; set; }
        public virtual NguoiDung NguoiDung { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Anh> Anhs { get; set; }
    }
}
