//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebMedia.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Anh
    {
        public int ID_Anh { get; set; }
        public string TenAnh { get; set; }
        public int ID_Album { get; set; }
    
        public virtual Album Album { get; set; }
    }
}
