//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebMedia.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietGoi
    {
        public int ID_ChiTetGoi { get; set; }
        public int ID_Goi { get; set; }
        public int ID_DichVu { get; set; }
    
        public virtual DichVu DichVu { get; set; }
        public virtual GoiDichVu GoiDichVu { get; set; }
    }
}
