//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebMedia.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GoiDichVu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GoiDichVu()
        {
            this.ChiTietGois = new HashSet<ChiTietGoi>();
            this.LichChups = new HashSet<LichChup>();
        }
    
        public int ID_Goi { get; set; }
        public string TenGoi { get; set; }
        public Nullable<double> Gia { get; set; }
        public Nullable<int> SoLuongAnh { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietGoi> ChiTietGois { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LichChup> LichChups { get; set; }
    }
}
