//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebMedia.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HoaDon
    {
        public int ID_HoaDon { get; set; }
        public int ID_LichChup { get; set; }
        public double Gia { get; set; }
        public Nullable<bool> TrangThaiThanhToan { get; set; }
    
        public virtual LichChup LichChup { get; set; }
    }
}
