//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebMedia.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LichChup
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LichChup()
        {
            this.HoaDons = new HashSet<HoaDon>();
        }
    
        public int ID_LichChup { get; set; }
        public int ID_KhachHang { get; set; }
        public int ID_NguoiChup { get; set; }
        public Nullable<System.DateTime> NgayDat { get; set; }
        public Nullable<System.DateTime> NgayChup { get; set; }
        public int ID_ChuDe { get; set; }
        public int ID_ChatBox { get; set; }
        public Nullable<bool> TrangThaiChup { get; set; }
        public int ID_Goi { get; set; }
    
        public virtual ChatBox ChatBox { get; set; }
        public virtual ChuDe ChuDe { get; set; }
        public virtual GoiDichVu GoiDichVu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HoaDon> HoaDons { get; set; }
        public virtual NguoiDung NguoiDung { get; set; }
        public virtual NguoiDung NguoiDung1 { get; set; }
    }
}
