//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebMedia.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NguoiDung
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NguoiDung()
        {
            this.Albums = new HashSet<Album>();
            this.LichChups = new HashSet<LichChup>();
            this.LichChups1 = new HashSet<LichChup>();
        }
    
        public int ID_NguoiDung { get; set; }
        public string HoTen { get; set; }
        public string STD { get; set; }
        public string DiaChi { get; set; }
        public string AnhDaiDien { get; set; }
        public string TaiKhoan { get; set; }
        public string MatKhau { get; set; }
        public string ID_Quyen { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Album> Albums { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LichChup> LichChups { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LichChup> LichChups1 { get; set; }
        public virtual Quyen Quyen { get; set; }
    }
}
