//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebMedia.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NoiDungChat
    {
        public int ID_NoiDungChat { get; set; }
        public int ID_NguoiDung { get; set; }
        public string NoiDung { get; set; }
        public Nullable<System.DateTime> ThoiGian { get; set; }
        public int ID_ChatBox { get; set; }
    
        public virtual ChatBox ChatBox { get; set; }
        public virtual NguoiDung NguoiDung { get; set; }
    }
}
